version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ton_transactions_db
    environment:
      POSTGRES_DB: ton_transactions
      POSTGRES_USER: ton_user
      POSTGRES_PASSWORD: ton_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ton_user -d ton_transactions"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ton_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
